---
- name: Enforce s3 bucket versioning on AWS account
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: List S3 buckets in AWS account
      amazon.aws.s3_bucket_info:
      register: result

    - debug:
        var: result
        
    - name: Enable versioning on S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: enabled
      loop: "{{ result.buckets }}"